### PR TITLE
Add support for the DISCO_F429ZI target

### PR DESCRIPTION
**Pull request by AlessandroA**
This PR depends on https://github.com/ARMmbed/mbed-os/pull/3397, so do not merge it yet!

As soon as the mbed OS PR will be merged, I'll also push the updated mbed-os.lib file here.

@meriac @niklas-arm @Patater @adustm

### CODE REVIEW

**Comment by AlessandroA** [comment]
@meriac @niklas-arm PR is no longer WIP and can be reviewed.
**Note: It still can't be merged though, as we need to wait for the mbed OS release.**

**Comment by mazimkhan** [comment]
retest uvisor

**Comment by mazimkhan** [comment]
retest uvisor

**Comment by AlessandroA** [comment]
Now depends on #30. This PR should not be merged until the new target works with the app.

**Comment by AlessandroA** [comment]
Closing as outdated.

**Comment by adustm** [comment]
Hello @AlessandroA 
Is the DISCO_F429ZI now supported in this example ?

Kind regards
Armelle

**Comment by AlessandroA** [comment]
Hi Armelle, this is now being tracked at https://github.com/ARMmbed/mbed-os-example-uvisor-thread/pull/52. We are reviewing the CI errors at the moment.

**Pull request closed without merging**
